version: 2.0
jobs:
  build:
    docker:
       - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          gradle test
      - run:
          gradle jar
      - store_test_results:
          path: . 
      - store_artifacts:
          path: /code/test-results
          destination: prefix
         
